import Head from "next/head";
import NavBar from "./nav/NavBar";
import { useIsFetching } from "react-query";
import LoadingLayout from "./loading/LoadingLayout";
import Footer from "./Footer";

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  const isFetching = useIsFetching();

  return (
    <div className="relative">
      <Head>
        <title>ASAP NEWS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {children}
      <Footer />
      {isFetching !== 0 && <LoadingLayout />}
    </div>
  );
};

export default Layout;
